### ISSUE TITLE
Problem load module lldp on  Alpine zabbix-server 3.4.15

### ISSUE THREAD

**Issue by roysbike** [zabbix-book/snmp_lldp#1]
Docker 
`FROM  zabbix/zabbix-server-mysql:alpine-3.4.15
`
`1:20190809:105846.739 cannot load module "lldp_get.so": Error relocating /var/lib/zabbix/modules//lldp_get.so: zbx_json_addobject: symbol not found`

**Comment by zhausong** [comment]
maybe you should rebuild it
https://github.com/zabbix-book/snmp_lldp/blob/master/soource/modules/Makefile
